[package]
name = "jolt-on-chain"
version = "0.1.0"
authors = ["Arithmic labs"]
edition = "2021"
description = "Doing recursion on Jolt proof to enable efficient on-chain verification."

[dependencies]
serde_json = "1.0"